using ContainerWeightlimitSetter.Settings;
using ContainerWeightlimitSetter.Utility;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Json;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using Noggog;

namespace ContainerWeightlimitSetter
{
    public class Program
    {
        
        private static Lazy<Settings.Settings> _lazySettings = null!;
        private static Settings.Settings Settings => _lazySettings.Value;

        public static JsonSerializerSettings JsonSerializerSettings = new();

        private const string QaContainerMarker = "QA";
        private const string VendorChestMarker = "Vendor";
        private const string MerchantChestMarker = "Merchant";
        
        public static Settings.ContainerWeightSettings ContainerWeightSettings => Settings.ContainerWeightSettings;
        
        public static WeightGeneratorSettings WeightGeneratorSettings => Settings.WeightGeneratorSettings;

        public static HashSet<IFormLinkGetter<IContainerGetter>>  IgnoredContainers => Settings.IgnoredContainers;
        
        public static async Task<int> Main(string[] args)
        {
            
            JsonSerializerSettings.AddMutagenConverters();
            //TODO: Implement Gamefolder Validation Checking for SKSE Plugin being installed
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "Settings.json",
                    out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            SkseExports skseExports = new();
            ContainerProcessor containerProcessor = new(state.LinkCache);
            
            var merchantFactions = state.LoadOrder.PriorityOrder.Faction().WinningOverrides()
                .Where(faction => !faction.MerchantContainer.IsNull).ToHashSet();
            
            var merchantContainers = containerProcessor.GetMerchantContainerFormKeys(merchantFactions,state.LinkCache);
            
            state.PatchMod.Containers.Set(
                state.LoadOrder.PriorityOrder.Container().WinningOverrides()
                .Where(container => container is {EditorID: not null, Weight: 0}
                                    && !container.EditorID.Contains(QaContainerMarker)
                                    && !container.EditorID
                                        .Contains(VendorChestMarker, StringComparison.OrdinalIgnoreCase)
                                    && !container.EditorID
                                        .Contains(MerchantChestMarker, StringComparison.OrdinalIgnoreCase)
                                    && !merchantContainers.Contains(container.FormKey)
                                    && !skseExports.ExportedIgnoredContainerEditorId(container)
                                    && (container.VirtualMachineAdapter?.Scripts.Count ?? 0) == 0 
                                    )
                .Select(container => container.DeepCopy())
                .Do(container =>
                {
                    container.Weight = containerProcessor.EstimateWeight(container);
                })
            );
            
            var skseExportsJson
                = JsonConvert.SerializeObject(skseExports,Formatting.Indented);
            
            var staticallyProcessedContainers
                = JsonConvert.SerializeObject(containerProcessor,Formatting.Indented);

            //TODO: Implement JSON Export for SKSE Plugin // Maybe ?
            
            Console.WriteLine(skseExportsJson);
            Console.WriteLine(staticallyProcessedContainers);

            var maxGeneratedWeight =  containerProcessor.ContainerMaxWeightDictionary.Max(entry => entry.Value);
            var minGeneratedWeight =  containerProcessor.ContainerMaxWeightDictionary.Min(entry => entry.Value);
            var averageGeneratedWeight =  containerProcessor.ContainerMaxWeightDictionary.Average(entry => entry.Value).Round();
            Console.WriteLine($"Max Generated Weight: {maxGeneratedWeight}");
            Console.WriteLine($"Min Generated Weight: {minGeneratedWeight}");
            Console.WriteLine($"Average Generated Weight: {averageGeneratedWeight}");

        }

    }
}
