using ContainerWeightlimitSetter.Utility;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;

namespace ContainerWeightlimitSetter
{
    public class Program
    {
        
        private static Lazy<Settings.Settings> _lazySettings = null!;
        private static Settings.Settings Settings => _lazySettings.Value;

        private const string QaContainerMarker = "QA";
        private const string VendorChestMarker = "Vendor";
        private const string MerchantChestMarker = "Merchant";
        
        public static Settings.ContainerWeightSettings ContainerWeightSettings => Settings.ContainerWeightSettings;

        public static HashSet<IFormLinkGetter<IContainerGetter>>  IgnoredContainers => Settings.IgnoredContainers;

       
        public static async Task<int> Main(string[] args)
        {
            
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "Settings.json",
                    out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "YourPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            
            SkseExports skseExports = new();
            ContainerProcessor containerProcessor = new();
            
            state.PatchMod.Containers.Set(
                state.LoadOrder.PriorityOrder.Container().WinningOverrides()
                .Where(container => container is {EditorID: not null, Weight: 0}
                                    && !container.EditorID.Contains(QaContainerMarker)
                                    && !container.EditorID
                                        .Contains(VendorChestMarker, StringComparison.OrdinalIgnoreCase)
                                    && !container.EditorID
                                        .Contains(MerchantChestMarker, StringComparison.OrdinalIgnoreCase)
                                    && !skseExports.ExportedIgnoredContainerEditorId(container)
                                    && (container.VirtualMachineAdapter?.Scripts.Count ?? 0) == 0 
                                    )
                .Select(container => container.DeepCopy())
                .Do(container =>
                {
                    //TODO: IMPLEMENT CONTAINER LOOT BASED WEIGHT LIMIT GENERATION
                    
                    container.Weight = containerProcessor.EstimateWeight(container);
                    Console.WriteLine($"Setting weight of {container.EditorID} to {container.Weight}");
                })
            );
            
            var skseExportsJson
                = JsonConvert.SerializeObject(skseExports,Formatting.Indented);
            
            var staticallyProcessedContainers
                = JsonConvert.SerializeObject(containerProcessor,Formatting.Indented);
            //TODO: Implement JSON Export for SKSE Plugin
            Console.WriteLine(skseExportsJson);
            Console.WriteLine(staticallyProcessedContainers);
            
        }
    }
}
