using ContainerWeightlimitSetter.Exceptions;
using ContainerWeightlimitSetter.Settings;
using ContainerWeightlimitSetter.Utility;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Json;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using NexusMods.Paths;
using Noggog;

namespace ContainerWeightlimitSetter
{
    public class Program
    {
        
        private static Lazy<Settings.Settings> _lazySettings = null!;
        private static Settings.Settings Settings => _lazySettings.Value;

        public static JsonSerializerSettings JsonSerializerSettings = new();

        private const string QaContainerMarker = "QA";
        private const string VendorChestMarker = "Vendor";
        private const string MerchantChestMarker = "Merchant";
        
        public static ContainerWeightSettings ContainerWeightSettings => Settings.ContainerWeightSettings;
        
        public static WeightGeneratorSettings WeightGeneratorSettings => Settings.WeightGeneratorSettings;

        public static HashSet<IFormLinkGetter<IContainerGetter>>  IgnoredContainers => Settings.IgnoredContainers;
        
        // ReSharper disable once InconsistentNaming
        private static SKSEConfigSettings skseConfigSettings => Settings.SKSEConfigSettings;
        
        public static async Task<int> Main(string[] args)
        {
            
            JsonSerializerSettings.AddMutagenConverters();
            
            return await SynthesisPipeline.Instance
                .AddRunnabilityCheck(CheckRunnability)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "Settings.json",
                    out _lazySettings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "ContainerWeightLimit.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            LoggingExports loggingExports = new(ContainerWeightSettings);
            ContainerProcessor containerProcessor = new(ContainerWeightSettings ,WeightGeneratorSettings, state.LinkCache);
            
            var merchantFactions = state.LoadOrder.PriorityOrder.Faction().WinningOverrides()
                .Where(faction => !faction.MerchantContainer.IsNull).ToHashSet();
            
            var merchantContainers = containerProcessor.GetMerchantContainerFormKeys(merchantFactions,state.LinkCache);
            
            state.PatchMod.Containers.Set(
                state.LoadOrder.PriorityOrder.Container().WinningOverrides()
                .Where(container => container is {EditorID: not null, Weight: 0}
                                    && !container.EditorID.Contains(QaContainerMarker)
                                    && !container.EditorID
                                        .Contains(VendorChestMarker, StringComparison.OrdinalIgnoreCase)
                                    && !container.EditorID
                                        .Contains(MerchantChestMarker, StringComparison.OrdinalIgnoreCase)
                                    && !merchantContainers.Contains(container.FormKey)
                                    && !loggingExports.ExportedIgnoredContainerEditorId(container)
                                    && (container.VirtualMachineAdapter?.Scripts.Count ?? 0) == 0 
                                    )
                .Select(container => container.DeepCopy())
                .Do(container =>
                {
                    container.Weight = containerProcessor.EstimateWeight(container);
                })
            );
            
            //Global for the SKSE Plugin to check if the Synthesis Patcher has been run
            state.PatchMod.Globals.Add(new GlobalInt(state.PatchMod)
            {
                EditorID = "ContainerWeightLimitsGenerated",
                Data = 42
            });
            
            
            var loggingExportsJson
                = JsonConvert.SerializeObject(loggingExports,Formatting.Indented);
            
            var staticallyProcessedContainers
                = JsonConvert.SerializeObject(containerProcessor,Formatting.Indented);
            
            loggingExports.ExportWeightGroups(state.LinkCache);
            
            Console.WriteLine(loggingExportsJson);
            Console.WriteLine(staticallyProcessedContainers);

            var maxGeneratedWeight =  containerProcessor.ContainerMaxWeightDictionary.Max(entry => entry.Value);
            var minGeneratedWeight =  containerProcessor.ContainerMaxWeightDictionary.Min(entry => entry.Value);
            var averageGeneratedWeight =  containerProcessor.ContainerMaxWeightDictionary.Average(entry => entry.Value).Round();
            Console.WriteLine($"Max Generated Weight: {maxGeneratedWeight}");
            Console.WriteLine($"Min Generated Weight: {minGeneratedWeight}");
            Console.WriteLine($"Average Generated Weight: {averageGeneratedWeight}");


            if (!skseConfigSettings.ExportSKSEConfig) return;
            var skseJsonExportString = JsonConvert.SerializeObject(
                new ExportForSKSE(skseConfigSettings,state.LinkCache),Formatting.Indented);
            Console.WriteLine($"Exporting SKSE config to SKSE plugin");
            var skseExcludesJsonFilePath = Path.Combine(state.DataFolderPath, new RelativePath("SKSE/Plugins/synthesis-container-weight-exclusions.json").ToNativeSeparators(OSInformation.FromCurrentRuntime()));
            Console.WriteLine($"Exporting SKSE configuration to \"{skseExcludesJsonFilePath}\"");
            try
            {
                File.WriteAllText(skseExcludesJsonFilePath, skseJsonExportString);
                Console.WriteLine("SKSE configuration exported successfully");
            } catch (Exception e)
            {
                Console.WriteLine("Failed to export SKSE configuration");
                Console.WriteLine(e.Message);
            }
            
        }
        
        public static void CheckRunnability(IRunnabilityState state)
        {
            var dataFolder = state.DataFolderPath;
            var skseDll = Path.Combine(dataFolder, new RelativePath("SKSE/Plugins/styyx-container-limit.dll").ToNativeSeparators(OSInformation.FromCurrentRuntime()));
            Console.WriteLine($"Checking for {skseDll}");
            if (!File.Exists(skseDll)) throw new MissingSKSEPluginException("Container Weight Limit Mod SKSE dependency is not installed. You can find it here: https://www.nexusmods.com/skyrimspecialedition/mods/176627",skseDll);
        }

    }
}
